apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-xray-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-xray-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-xray-rolebinding
subjects:
  - kind: ServiceAccount
    name: crd-xray-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: crd-xray-role
  apiGroup: rbac.authorization.k8s.io