apiVersion: v1
kind: Service
metadata:
  name: crd-xray-agent-external
  namespace: default
spec:
  selector:
    app: crd-xray
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: NodePort 